config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html]
  root to: 'sessions#new'

  resources :dashboard, only: [:index]
  
  resources :common_inquiries, except: :show do
    collection do
      get 'search'
    end
  end

  resources :sessions, only: [:new, :create] do
    collection do
      get 'logout', to: 'sessions#destroy'
    end
  end

  resources :inquiries do
    collection do
      get 'unregister_inquiries'
      get 'related_inquiries'
      get 'qa_search'
      get 'most_recent_search'
      get 'unregister_new'
      get 'inquiry_search'
      post 'unregister_create'
      patch 'unregister_update'
    end

    member do
      get 'resurrect'
      get 'approve'
      get 'approve_cancel'
      get 'unregister_edit'
      delete 'unregister_destroy'
    end
  end

  resources :users, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :systems, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :inquiry_classifications, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :inquirier_kinds, except: :show do
    member do
      get 'resurrect'
    end
  end
end

app/models/inquiry_classification.rb
class InquiryClassification < ApplicationRecord
  has_many :inquiries, foreign_key: 'inquiry_classification_id'

  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }

  scope :without_deleted, -> {
    where(deleted_at: nil).order(id: :asc)
  }

  def logical_delete
    self.update!(deleted_at: DateTime.now)
  end

  def resurrect
    self.update!(deleted_at: nil)
  end

  def deleted?
    self.deleted_at.present?
  end
end

app/controllers/inquiry_classifications_controller.rb
class InquiryClassificationsController < ApplicationController
  PER = 10

  def index
    @inquiry_classifications = InquiryClassification.order(id: :asc).page(params[:page]).per(PER)
  end

  def new
    @inquiry_classification = InquiryClassification.new
    render 'save_modal'
  end

  def create
    @inquiry_classification = InquiryClassification.new(inquiry_classification_params)
    @inquiry_classification.save!
    respond_to do |format|
      format.html
      format.js { render js: "window.location.href = '#{inquiry_classifications_path}'" }
    end
  rescue ActiveRecord::RecordInvalid => e
    respond_to do |format|
      format.html
      format.js { render partial: 'shared/modal_errors.js.erb', locals: { model: @inquiry_classification } }
    end
  end

  def edit
    @inquiry_classification = InquiryClassification.find(params[:id])
    render 'save_modal'
  end

  def update
    @inquiry_classification = InquiryClassification.find(params[:id])
    @inquiry_classification.update!(inquiry_classification_params)
    respond_to do |format|
      format.html
      format.js { render js: "window.location.href = '#{inquiry_classifications_path}'" }
    end
  rescue ActiveRecord::RecordInvalid => e
    respond_to do |format|
      format.html
      format.js { render partial: 'shared/modal_errors.js.erb', locals: { model: @inquiry_classification } }
    end
  end

  def destroy
    inquiry_classification = InquiryClassification.find(params[:id])
    inquiry_classification.logical_delete
    
    redirect_to inquiry_classifications_path
  end

  def resurrect
    inquiry_classification = InquiryClassification.find(params[:id])
    inquiry_classification.resurrect

    redirect_to inquiry_classifications_path
  end

  private

  def inquiry_classification_params
    params.require(:inquiry_classification).permit(:name)
  end
end

app/helpers/inquiry_classifications_helper.rb
module InquiryClassificationsHelper
  include ApplicationHelper

  def inquiry_classification_operate_button(classification)
    str = ''
    if classification.deleted?
      str += resurrect_button(resurrect_inquiry_classification_path(classification.id))
      return str.html_safe
    end
    str += edit_button(edit_inquiry_classification_path(classification.id), 'get', true)
    str += delete_button(inquiry_classification_path(classification.id))
    
    return str.html_safe
  end
end

app/views/inquiry_classifications/_form.html.erb
<div id="inquiry_classification_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" area-modal="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">問合せ分類の保存</h4>
      </div>

      <%= form_with model: @inquiry_classification, local: false do |f| %>
        <div id="errors"></div>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :name, '分類名' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="modal-footer">
          <%= button_tag '閉じる', type: 'button', class: 'btn btn-default', data: {:'bs-dismiss' => "modal"} %>
          <%= save_button_tag(f) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/inquiry_classifications/index.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <div class="container-fluid">
      <h4 class="m-0 text-dark">問合せ分類一覧</h4>
    </div>
  </section>

  <section class="content">
    <div class="container-fluid">
      
      <div class="card">
        <div class="card-header">
          <div class="text-right">
            <%= new_button(new_inquiry_classification_path, 'get', true) %>
          </div>
        </div>

        <div class="card-body p-0">
          <table class="table table-striped">
            <thead>
              <tr class="bg-secondary">
                <th>No</th>
                <th>分類名</th>
                <th>削除日時</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @inquiry_classifications.each_with_index do |classification, i| %>
                <tr>
                  <td><%= calc_row_number(@inquiry_classifications, i) %></td>
                  <td><%= classification.name %></td>
                  <td><%= classification.deleted_at.try!(:strftime, '%Y-%m-%d %H:%M:%S') %></td>
                  <td><%= inquiry_classification_operate_button(classification) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @inquiry_classifications %>
        </div>
      </div>
    </div>
  </section>
</div>

<div id="modal_area">
</div>

app/views/inquiry_classifications/save_modal.js.erb
$('#modal_area').html("<%= j(render 'inquiry_classifications/form') %>");
$('#inquiry_classification_modal').modal('show');