config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html]
  root to: 'sessions#new'

  resources :dashboard, only: [:index]
  
  resources :common_inquiries, except: :show do
    collection do
      get 'search'
    end
  end

  resources :sessions, only: [:new, :create] do
    collection do
      get 'logout', to: 'sessions#destroy'
    end
  end

  resources :inquiries do
    collection do
      get 'unregister_inquiries'
      get 'related_inquiries'
      get 'qa_search'
      get 'most_recent_search'
      get 'unregister_new'
      get 'inquiry_search'
      post 'unregister_create'
      patch 'unregister_update'
    end

    member do
      get 'resurrect'
      get 'approve'
      get 'approve_cancel'
      get 'unregister_edit'
      delete 'unregister_destroy'
    end
  end

  resources :users, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :systems, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :inquiry_classifications, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :inquirier_kinds, except: :show do
    member do
      get 'resurrect'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true, length: { maximum: 10 }
  validates :login_id, presence: true, uniqueness: true, length: { maximum: 10 }, format: {with: /\A[a-zA-Z0-9]+\z/}
  validates :password, confirmation: true, allow_blank: true, length: { minimum: 4 }
  validates :password_confirmation, presence: true, allow_blank: true

  scope :without_deleted, -> {
    where(deleted_at: nil).order(id: :asc)
  }

  def logical_delete
    self.update!(deleted_at: DateTime.now)
  end

  def resurrect
    self.update!(deleted_at: nil)
  end

  def deleted?
    self.deleted_at.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  PER = 10

  def index
    @users = User.order(id: :asc).page(params[:page]).per(PER)
  end

  def new
    @user = User.new
    render 'save_modal'
  end

  def create
    @user = User.new(user_params)
    @user.save!
    respond_to do |format|
      format.html
      format.js { render js: "window.location.href = '#{users_path}'" }
    end
  rescue ActiveRecord::RecordInvalid => e
    respond_to do |format|
      format.html
      format.js { render partial: 'shared/modal_errors.js.erb', locals: { model: @user } }
    end
  end

  def edit
    @user = User.find(params[:id])
    render 'save_modal'
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    respond_to do |format|
      format.html
      format.js { render js: "window.location.href = '#{users_path}'" }
    end
  rescue ActiveRecord::RecordInvalid => e
    respond_to do |format|
      format.html
      format.js { render partial: 'shared/modal_errors.js.erb', locals: { model: @user } }
    end
  end

  def destroy
    user = User.find(params[:id])
    user.logical_delete

    redirect_to users_path
  end

  def resurrect
    user = User.find(params[:id])
    user.resurrect

    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :login_id, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  include ApplicationHelper

  def user_operate_button(user)
    str = ''
    if user.deleted?
      str += resurrect_button(resurrect_user_path(user.id))
      return str.html_safe
    end
    str += edit_button(edit_user_path(id: user.id), 'get', true)
    unless user == current_user
      str += delete_button(user_path(id: user.id))
    end
    
    return str.html_safe
  end
end

app/views/users/_form.html.erb
<div id="user_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" area-modal="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">ユーザの保存</h4>
      </div>

      <%= form_with model: @user, local: false do |f| %>
        <div id="errors"></div>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :name, 'ユーザ名' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :login_id, 'ログインID' %>
            <%= f.text_field :login_id, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>
        <div class="modal-footer">
          <%= button_tag '閉じる', type: 'button', class: 'btn btn-default', data: {:'bs-dismiss' => "modal"} %>
          <%= save_button_tag(f) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <div class="container-fluid">
      <h4 class="m-0 text-dark">ユーザ一覧</h4>
    </div>
  </section>

  <section class="content">
    <div class="container-fluid">
      
      <div class="card">
        <div class="card-header">
          <div class="text-right">
            <%= new_button(new_user_path, 'get', true) %>
          </div>
        </div>

        <div class="card-body p-0">
          <table class="table table-striped">
            <thead>
              <tr class="bg-secondary">
                <th>No</th>
                <th>ユーザ名</th>
                <th>削除日時</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @users.each_with_index do |user, i| %>
                <tr>
                  <td><%= calc_row_number(@users, i) %></td>
                  <td><%= user.name %></td>
                  <td><%= user.deleted_at.try!(:strftime, '%Y-%m-%d %H:%M:%S') %></td>
                  <td><%= user_operate_button(user) %></td>
                </tr>
              <% end %> 
            </tbody>
          </table>
          <%= paginate @users %>
        </div>
      </div>
    </div>
  </section>
</div>

<div id="modal_area">
</div>

app/views/users/new.js.erb
$('#modal_area').html("<%= j(render 'users/form') %>");
$('#user_modal').modal('show');

app/views/users/save_modal.js.erb
$('#modal_area').html("<%= j(render 'users/form') %>");
$('#user_modal').modal('show');