config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html]
  root to: 'sessions#new'

  resources :dashboard, only: [:index]
  
  resources :common_inquiries, except: :show do
    collection do
      get 'search'
    end
  end

  resources :sessions, only: [:new, :create] do
    collection do
      get 'logout', to: 'sessions#destroy'
    end
  end

  resources :inquiries do
    collection do
      get 'unregister_inquiries'
      get 'related_inquiries'
      get 'qa_search'
      get 'most_recent_search'
      get 'unregister_new'
      get 'inquiry_search'
      post 'unregister_create'
      patch 'unregister_update'
    end

    member do
      get 'resurrect'
      get 'approve'
      get 'approve_cancel'
      get 'unregister_edit'
      delete 'unregister_destroy'
    end
  end

  resources :users, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :systems, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :inquiry_classifications, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :inquirier_kinds, except: :show do
    member do
      get 'resurrect'
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.present? && model.errors.any? %>
  <div class="alert alert-danger">
    <i class="fas fa-exclamation-triangle"></i>&nbsp;エラーがあります
    <ul>
      <% model.errors.full_messages.each  do |error_message| %>
          <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if model.present? && model.errors.any? %>
  <div class="alert alert-danger">
    <i class="fas fa-exclamation-triangle"></i>&nbsp;エラーがあります
    <ul>
      <% model.errors.full_messages.each  do |error_message| %>
          <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_modal_errors.js.erb
$('#errors').html("<%= j(render partial: 'shared/error_messages', locals: { model: model }) %>");

app/views/shared/_side_nav.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <%= link_to dashboard_index_path, class: 'brand-link text-decoration-none', style:'line-height: 1.5;' do %>
    <span class="brand-text">
      <%= sanitize(Rails.configuration.x.app_setting[:application_name]) %>
    </span>
  <% end %>

  <div class="sidebar">
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to dashboard_index_path, class: 'nav-link' do %>
            <i class="nav-icon far fa-chart-bar fa-lg"></i> ダッシュボード
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to unregister_inquiries_inquiries_path, class: 'nav-link' do %>
            <i class="nav-icon fas fa-bell fa-lg"></i> 新着情報
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to inquiries_path, class: 'nav-link' do %>
            <i class="nav-icon fas fa-list fa-lg"></i> 問合せ一覧
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to users_path, class: 'nav-link' do %>
            <i class="nav-icon fas fa-user-edit fa-lg"></i> ユーザ管理
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to systems_path, class: 'nav-link' do %>
            <i class="nav-icon fas fa-laptop-code"></i> システム管理
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to inquiry_classifications_path, class: 'nav-link' do %>
            <i class="nav-icon fas fa-tag"></i> 問合せの分類管理
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to inquirier_kinds_path, class: 'nav-link' do %>
            <i class="nav-icon fas fa-user-tag"></i> 問合せ者の分類管理
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to common_inquiries_path, class: 'nav-link' do %>
            <i class="nav-icon fas fa-bookmark"></i> よくある問合せ
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</aside>

app/views/shared/_simple_error.html.erb
<!-- flashメッセージを表示させる簡易的なエラー表示  -->
<% if flash.present? %>
  <div class="alert alert-danger alert-dismissible">
    <i class="fas fa-exclamation-triangle"></i>&nbsp;
    <% flash.each do |type, message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>

app/views/shared/_top_nav.html.erb
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item d-flex align-items-center me-4">
      <i class="nav-icon fas fas fa-solid fa-user me-1"></i>
      <%= current_user.name %>
    </li>
    <li class="nav-item">
      <%= link_to logout_sessions_path, mathod: :get, class: 'btn btn-outline-danger' do %>
        ログアウト&nbsp;<i class="nav-icon fas fas fa-sign-out-alt fa-lg"></i>
      <% end %>
    </li>
  </ul>
</nav>