config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html]
  root to: 'sessions#new'

  resources :dashboard, only: [:index]
  
  resources :common_inquiries, except: :show do
    collection do
      get 'search'
    end
  end

  resources :sessions, only: [:new, :create] do
    collection do
      get 'logout', to: 'sessions#destroy'
    end
  end

  resources :inquiries do
    collection do
      get 'unregister_inquiries'
      get 'related_inquiries'
      get 'qa_search'
      get 'most_recent_search'
      get 'unregister_new'
      get 'inquiry_search'
      post 'unregister_create'
      patch 'unregister_update'
    end

    member do
      get 'resurrect'
      get 'approve'
      get 'approve_cancel'
      get 'unregister_edit'
      delete 'unregister_destroy'
    end
  end

  resources :users, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :systems, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :inquiry_classifications, except: :show do
    member do
      get 'resurrect'
    end
  end

  resources :inquirier_kinds, except: :show do
    member do
      get 'resurrect'
    end
  end
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :system
  belongs_to :user
  belongs_to :inquiry_classification
  belongs_to :inquirier_kind
  belongs_to :approver, class_name: 'User', optional: true
  belongs_to :parent_inquiry, class_name: 'Inquiry', optional: true

  validates :inquiry_date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :company_name, presence: true, length: { maximum: 30 }
  validates :telephone_number, presence: true, length: { maximum: 13 }
  validates :sub_telephone_number, length: { maximum: 13 }
  validates :inquirier_name, presence: true, length: { maximum: 30 }
  validates :question, presence: true, length: { maximum: 500 }
  validates :answer, presence: true, length: { maximum: 500 }

  enum is_completeds: { incomplete: false, complete: true }
  enum inquiry_method_ids: { telephone: 1, mail: 2, direct: 3, other: 4 }

  scope :without_deleted, -> { where(deleted_at: nil) }

  def system_name
    return system.name
  end

  def user_name
    return user.name
  end

  def approver_name
    return '' if self.approver.blank?
    return self.approver.name
  end

  def approve_datetime
    return '' if self.approve_at.blank?
    return self.approve_at.try!(:strftime, '%Y-%m-%d %H:%M')
  end

  def inquiry_datetime_text
    date = self.inquiry_date.strftime('%Y-%m-%d')
    time = self.start_time.strftime('%H:%M')

    return date + ' ' + time
  end

  def display_parent_inquiry
    return nil if parent_inquiry.blank?
    return inquiry_datetime_text + ' ' + parent_inquiry.company_name
  end

  def parent_inquiries
    parents = []
    inquiry = self.parent_inquiry
    loop do
      if inquiry.blank?
        break
      end

      parents << inquiry
      inquiry = inquiry.parent_inquiry
    end

    return parents
  end

  def logical_delete
    self.update!(deleted_at: DateTime.now)
  end

  def resurrect
    self.update!(deleted_at: nil)
  end

  def deleted?
    self.deleted_at.present?
  end

  def approve(user)
    self.update!(
      approver_id: user.id,
      approve_at: Time.zone.now
    )
  end

  def approve_cancel
    self.update!(
      approver_id: nil,
      approve_at: nil,
    )
  end

  def self.complete_options
    return { '未完了' => is_completeds[:incomplete], '完了' => is_completeds[:complete], }
  end

  def self.inquiry_method_options
    return {
      '電話' => inquiry_method_ids[:telephone],
      'メール' => inquiry_method_ids[:mail],
      '直接' => inquiry_method_ids[:direct],
      'その他' => inquiry_method_ids[:other],
    }
  end

  def self.search_related_inquiries(except_id, tel_no, sub_tel_no)
    except_id = except_id.blank? ? 0 : except_id
    inquiries = without_deleted
                  .where.not(id: except_id)
                  .where(telephone_number: tel_no)
                  .or(
                    where(telephone_number: sub_tel_no)
                  )
                  .order(inquiry_date: :desc)
                  .order(start_time: :desc)

    return inquiries
  end

  def self.get_prev_inquiry(telephone)
    inquiry = Inquiry.where(telephone_number: telephone)
                      .or(Inquiry.where(sub_telephone_number: telephone))
                      .order(inquiry_date: :desc)
                      .order(start_time: :desc)
                      .first

    return inquiry
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  protect_from_forgery only: :unregister_create

  require 'csv'
  PER = 10
  UNREGISTER_PER = 9
  MOST_RECENT = 100
  
  def index
    set_select_box_items
    @q = Inquiry.ransack(params[:q])
    @inquiries = @q.result
                   .includes(:system)
                   .order(inquiry_date: :desc)
                   .order(start_time: :desc)
                   .page(params[:page])
                   .per(PER)
    if params[:export_csv]
      csv = generate_csv(@inquiries)
      send_data(csv, type: 'text/csv', filename: 'inquiries.csv')
    elsif params[:export_excel]
      render xlsx: 'index'
    end
  end

  def unregister_inquiries
    @inquiries = UnregisterInquiry.search(current_user)
                                  .page(params[:page])
                                  .per(UNREGISTER_PER)
                                  
    flash.now[:message] = '新着の問合せはありません。' if @inquiries.blank?
  end

  def show
    current_user
    @inquiry = Inquiry.find(params[:id])
  end

  def new
    set_select_box_items
    @inquiry = Inquiry.new
    @inquiry.inquiry_date = Date.today
    @inquiry.start_time = Time.zone.now.strftime('%H:%M')
    @inquiry.end_time = Time.zone.now.strftime('%H:%M')
  end

  def unregister_new
    set_select_box_items
    @unregister_inquiry = UnregisterInquiry.find(params[:id])
    @inquiry = Inquiry.new
    @inquiry.user_id = @unregister_inquiry.user_id
    @inquiry.inquiry_method_id = Inquiry.inquiry_method_ids[:telephone]
    @inquiry.inquiry_date = @unregister_inquiry.inquiry_date.try!(:strftime, '%Y-%m-%d')
    @inquiry.start_time = @unregister_inquiry.start_time.try!(:strftime, '%H:%M')
    @inquiry.end_time = @unregister_inquiry.end_time.try!(:strftime, '%H:%M')
    @inquiry.company_name = @unregister_inquiry.company_name
    @inquiry.inquirier_name = @unregister_inquiry.inquirier_name
    @inquiry.telephone_number = @unregister_inquiry.telephone_number
    @inquiry.inquirier_kind_id = @unregister_inquiry.inquirier_kind_id
    @inquiry.is_completed = @unregister_inquiry.is_completed

    render :new
  end

  def create
    @inquiry = Inquiry.new(inquiries_params)
    @inquiry.save!

    if params[:unregister_inquiry_id].present?
      unregister_inquiry = UnregisterInquiry.find(params[:unregister_inquiry_id])
      unregister_inquiry.destroy!
    end

    redirect_to action: :index
  rescue ActiveRecord::RecordInvalid => e
    set_select_box_items
    
    render :new
  end

  def unregister_create
    unregister_inquiry = UnregisterInquiry.new(unregister_params)
    unregister_inquiry.save!

    render state: 200, json: {}
  rescue ActiveRecord::RecordInvalid => e
    render state: 500, json: {}
  end

  def edit
    set_select_box_items
    @inquiry = Inquiry.find(params[:id])
    @inquiry.start_time = @inquiry.start_time.strftime('%H:%M')
    @inquiry.end_time = @inquiry.end_time.strftime('%H:%M')
  end

  def unregister_edit
    if @unregister_inquiry = UnregisterInquiry.find_by(id: params[:id])
      set_select_box_items
      
      if @unregister_inquiry.user_id.blank?
        @unregister_inquiry.update!(user_id: current_user.id)

        ActionCable.server.broadcast("cti_channel", { is_modal_close: true })
      end

      @inquiries = Inquiry.includes(:system)
                          .includes(:user)
                          .includes(:inquiry_classification)
                          .where(telephone_number: @unregister_inquiry.telephone_number)
                          .order(inquiry_date: :desc)
                          .order(start_time: :desc)
                          .limit(5)

      @q = Inquiry.ransack(params[:q])

      render :unregister_edit and return
    end

    redirect_to action: :unregister_inquiries
  end

  def update
    @inquiry = Inquiry.find(params[:id])
    @inquiry.update!(inquiries_params)

    redirect_to action: :index
  rescue ActiveRecord::RecordInvalid => e
    set_select_box_items
    
    render :edit
  end

  def unregister_update
    current_user
    if unregister_inquiry = UnregisterInquiry.find_by(id: params[:id], user_id: @current_user.id)
      is_completed = params[:completed].present?
      unregister_inquiry.update!(is_completed: is_completed, end_time: Time.now.strftime('%H:%M'))

      redirect_to unregister_new_inquiries_path(id: unregister_inquiry.id) and return
    end
    
    redirect_to action: :unregister_inquiries
  end

  def destroy
    inquiry = Inquiry.find(params[:id])
    inquiry.logical_delete

    redirect_to action: :index
  end

  def unregister_destroy
    unregister_inquiry = UnregisterInquiry.find(params[:id])
    unregister_inquiry.destroy!

    redirect_to action: :unregister_inquiries
  end

  def resurrect
    inquiry = Inquiry.find(params[:id])
    inquiry.resurrect

    redirect_to action: :index
  end

  def related_inquiries
    @inquiries = Inquiry.search_related_inquiries(params[:except_id], params[:telephone_number], params[:sub_telephone_number])
    render 'related_inquiries'
  end

  # unregister_editで利用
  def inquiry_search
    @q = Inquiry.ransack(params[:q])
    @inquiries = @q.result.select(:question, :answer)

    render json: @inquiries
  end

  def qa_search
    if params[:question].blank? && params[:answer].blank?
      render json: [].to_json
      return 
    end
    inquiries = Inquiry.without_deleted
                       .where(system_id: params[:system_id])
                       .where('question LIKE ?', "%#{params[:question]}%")
                       .where('answer LIKE ?', "%#{params[:answer]}%")
                       .order(inquiry_date: :desc)
                       .order(start_time: :desc)
    render json: inquiries.to_json
  end

  def most_recent_search
    inquiries = Inquiry.without_deleted
                       .where(system_id: params[:system_id])
                       .order(inquiry_date: :desc)
                       .order(start_time: :desc)
                       .limit(MOST_RECENT)
    render json: inquiries.to_json
  end

  def approve
    inquiry = Inquiry.find(params[:id])
    inquiry.approve(current_user)

    redirect_to action: :index
  end

  def approve_cancel
    inquiry = Inquiry.find(params[:id])
    inquiry.approve_cancel

    redirect_to action: :index
  end

  private

  def search_params
    params.require(:q).permit!
  end

  def generate_csv(inquiries)
    csv_data = CSV.generate(force_quotes: true) do |csv|
      header = %w(No 着信日時 システム名 問合せ元 担当者 電話番号 電話番号（予備） 連絡方法 問合せ元種別 問合せ内容 回答者 回答内容 問合せ分類 完了状況)
      csv << header
      inquiries.order(id: :asc).each do |inquiry|
        row = []
        row << inquiry.id
        row << inquiry.inquiry_datetime_text
        row << inquiry.company_name
        row << inquiry.inquirier_name
        row << inquiry.telephone_number
        row << inquiry.sub_telephone_number
        row << Inquiry.inquiry_method_options.key(inquiry.inquiry_method_id)
        row << inquiry.inquirier_kind.name
        row << inquiry.question
        row << inquiry.user_name
        row << inquiry.answer
        row << inquiry.inquiry_classification.name
        row << Inquiry.complete_options.key(inquiry.is_completed)

        csv << row
      end
    end
  end

  def inquiries_params
    params.require(:inquiry).permit(
      :inquiry_date, :start_time, :end_time,
      :system_id, :user_id, :inquiry_classification_id, :inquiry_method_id,
      :company_name, :telephone_number, :sub_telephone_number, :inquirier_name, :inquirier_kind_id,
      :question, :answer, :parent_inquiry_id, :is_completed
    )
  end

  def unregister_params
    params.permit(
      :company_name, :telephone_number, :inquirier_name, :inquirier_kind_id,
      :inquiry_date, :start_time, :unknown_number_status
    )
  end

  def set_select_box_items
    @systems = System.without_deleted.pluck(:name, :id)
    @users = User.without_deleted.pluck(:name, :id)
    @inquiry_classifications = InquiryClassification.without_deleted.pluck(:name, :id)
    @inquirier_kinds = InquirierKind.without_deleted.pluck(:name, :id)
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
  def build_inquiry_related_text(inquiry)
    str = ''
    str += inquiry.inquiry_datetime_text
    str += ' '
    str += inquiry.company_name
    return str
  end

  def inquiry_operate_button(inquiry)
    str = ''
    str = detail_button(inquiry_path(inquiry), 'get', true)
    if inquiry.deleted?
      str += resurrect_button(resurrect_inquiry_path(inquiry))
      return str.html_safe
    end
    str += edit_button(edit_inquiry_path(inquiry.id), 'get', false, edit_inquiry_path(inquiry))
    str += delete_button(inquiry_path(inquiry.id))
    
    return str.html_safe
  end

  def inquiry_show_operate_button(inquiry, user)
    str = ''
    if inquiry.deleted?
      str += resurrect_button(resurrect_inquiry_path(inquiry))
      return str.html_safe
    end
    str += edit_button(edit_inquiry_path(inquiry.id), 'get', false, edit_inquiry_path(inquiry))
    
    if user != inquiry.user
      if inquiry.approver.blank?
        str += approve_button(approve_inquiry_path(inquiry))
      else
        str += approve_cancel_button(approve_cancel_inquiry_path(inquiry))
      end
    end

    return str.html_safe
  end

  def inquiry_datetime(inquiry)
    return inquiry.inquiry_date.strftime('%Y-%m-%d') + ' ' + inquiry.start_time.strftime('%H:%M') + ' ～ ' + inquiry.end_time.strftime('%H:%M')
  end
end

app/views/inquiries/_parent_inquiries.html.erb
<div class="accordion" id="parent_inquiries">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button bg-warning" type="button" data-bs-toggle="collapse" data-bs-target="#parents" aria-expanded="true" aria-controls="parents">
        <strong>関連する問合せがあります</strong>
      </button>
    </h2>
    <div id="parents" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#parent_inquiries">
      <div class="accordion-body p-0">
        <table class="table table-bordered">
          <thead>
            <tr class="bg-secondary">
              <th>着信日時</th>
              <th>システム名</th>
              <th>担当者</th>
              <th>質問</th>
              <th>回答者</th>
              <th>回答</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            <% parent_inquiries.each do |inquiry| %>
              <tr>
                <td><%= @inquiry.inquiry_datetime_text %></td>
                <td><%= @inquiry.system.short_name %></td>
                <td><%= @inquiry.inquirier_name %></td>
                <td><%= @inquiry.question %></td>
                <td><%= @inquiry.user_name %></td>
                <td><%= @inquiry.answer %></td>
                <td><%= edit_button(edit_inquiry_path(inquiry), 'get', false, false) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/inquiries/_related_inquiries_modal.html.erb
<div id="related_inquiries_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" area-modal="true">
  <div class="modal-dialog xlarge_modal" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="container-fluid">
          <h4 class="modal-title">関連する問合せ</h4>
        </div>
      </div>

      <div class="modal-body p-0">
        <table class="table table-striped">
          <thead>
            <tr class="bg-secondary">
              <th>着信日時</th>
              <th>会社名</th>
              <th>担当者</th>
              <th>システム名</th>
              <th>問合せ内容</th>
              <th>回答内容</th>
              <th>回答者</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @inquiries.each do |inquiry| %>
              <tr>
                <td><%= inquiry.inquiry_datetime_text %></td>
                <td><%= inquiry.company_name %></td>
                <td><%= inquiry.inquirier_name %></td>
                <td><%= inquiry.system_name %></td>
                <td><%= inquiry.question %></td>
                <td><%= inquiry.answer %></td>
                <td><%= inquiry.user_name %></td>
                <td>
                  <%= button_tag '選択', type: 'button', class: 'btn btn-info', onclick: 'javascript: selectedRelatedInquiry(event);' %>
                  <%= hidden_field_tag :inquiry_id, inquiry.id %>
                  <%= hidden_field_tag :inquiry_related_text, build_inquiry_related_text(inquiry) %>
                </td>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="modal-footer">
        <%= button_tag '閉じる', type: 'button', class: 'btn btn-default', data: {:'bs-dismiss' => "modal"} %>
      </div>
    </div>
  </div>
</div>
<script>

  function selectedRelatedInquiry(event) {
    const selectBtn = event.currentTarget;
    const inquiryId = $(selectBtn).next().val();
    const inquiryRelatedText = $(selectBtn).next().next().val();

    $('#inquiry_parent_inquiry_id').val(inquiryId);
    $('#relation_text').val(inquiryRelatedText);

    $('#related_inquiries_modal').modal('hide');
  }

</script>

app/views/inquiries/edit.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <div class="container-fluid">
      <h4 class="m-0 text-dark">問合せ編集</h4>
    </div>
  </section>

  <section class="content">
    <%= render partial: 'form' %>
  </section>
</div>

<%= render partial: 'search_inquiry_modal' %>

<%= javascript_pack_tag 'inquiries/form' %>

<div id="modal_area">
</div>

app/views/inquiries/new.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <div class="container-fluid">
      <h4 class="m-0 text-dark">問合せ登録</h4>
    </div>
  </section>

  <section class="content">
    <%= render partial: 'form' %>
  </section>
</div>

<%= render partial: 'search_inquiry_modal' %>

<%= javascript_pack_tag 'inquiries/form' %>

<div id="modal_area">
</div>

app/views/inquiries/unregister_edit.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <div class="container-fluid">
      <h4 class="m-0 text-dark">応対中</h4>
    </div>
  </section>

  <section class="content">
    <div class="container-fluid">
      <%= form_with model: @unregister_inquiry, url: unregister_update_inquiries_path, method: :patch do |f| %>
        <div class="row">
          <div class="col col-sm-5">
            <div class="card">
              <div class="card-header bg-secondary">
                問合せ元情報
              </div>
              <div class="card-body">
                <ul class="list-group fs-5">
                  <li class="list-group-item">
                    <i class="fas fa-clock mr-3"></i> <%= @unregister_inquiry.inquiry_datetime %>
                    <%= f.hidden_field :start_time, value: @unregister_inquiry.start_time.strftime('%H:%M'), id: 'start_time' %>
                  </li>
                  <li class="list-group-item">
                    <i class="fas fa-industry mr-3"></i> <%= @unregister_inquiry.company_name %>
                  </li>
                  <li class="list-group-item">
                    <i class="fas fa-user-tie mr-3"></i> <%= @unregister_inquiry.inquirier_name %>
                  </li>
                  <li class="list-group-item">
                    <i class="fas fa-phone mr-3"></i> <%= @unregister_inquiry.telephone_number %>
                  </li>
                  <li class="list-group-item">
                    <i class="fas fa-user-friends mr-3"></i> <%= @unregister_inquiry.inquirier_kind.try!(:name) %>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          <div class="col col-sm-7 pl-4">
            <h1 id="timer" class="display-1"><%= @unregister_inquiry.elapsed_time.strftime('%H:%M:%S') %></h1>
            <hr>
            <%= form_with url: unregister_update_inquiries_path do |f| %>
              <%= f.hidden_field :id, value: @unregister_inquiry.id %>
              <%= f.submit '完了', class: 'btn btn-primary btn-lg w-25', name: 'completed' %>
              <%= f.submit '未完了', class: 'btn btn-danger btn-lg w-25' %>
            <% end %>
            <br>
            <div class="mt-2">
              <button type="button" class="btn btn-success btn-lg w-25" data-bs-toggle="modal" data-bs-target="#search_inquiry_modal">検索</button>
              <%= link_to '戻る', unregister_inquiries_inquiries_path, class: 'btn btn-secondary btn-lg w-25' %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col col-sm-12">
            <h5>過去の問合せ（直近5件表示）</h5>
            <div class="card">
              <div class="card-body p-0">
                <table class="table table-striped">
                  <thead>
                    <tr class="bg-secondary">
                      <th>着信日時</th>
                      <th>システム名</th>
                      <th>担当者</th>
                      <th>問合せ内容</th>
                      <th>回答内容</th>
                      <th>回答者</th>
                      <th>分類</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @inquiries.each do |inquiry| %>
                      <tr>
                        <td><%= inquiry.inquiry_datetime_text %></td>
                        <td><%= inquiry.system.short_name %></td>
                        <td><%= inquiry.inquirier_name %></td>
                        <td><%= inquiry.question %></td>
                        <td><%= inquiry.answer %></td>
                        <td><%= inquiry.user.name %></td>
                        <td><%= inquiry.inquiry_classification.name %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </section>
</div>

<div id="modal_area">
  <div id="search_inquiry_modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" area-modal="true">
    <div class="modal-dialog xlarge_modal" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <div class="container-fluid">
            <h4 class="modal-title">問合せ検索</h4>
            <br />
            
            <%= search_form_for @q, url: inquiry_search_inquiries_path, class: 'form-horizontal', id: 'search_form' do |f| %>
              <div class="row">
                <div class='form-group col col-sm-2'>
                  <%= f.label :system_id_eq, 'システム' %>
                  <%= f.select :system_id_eq, @systems, { include_blank: 'すべて' }, { class: 'form-control' } %>
                </div>
                <div class='form-group col col-sm-2'>
                  <%= f.label :inquiry_classification_id_eq, '問合せ種類' %>
                  <%= f.select :inquiry_classification_id_eq, @inquiry_classifications, { include_blank: 'すべて' }, { class: 'form-control' } %>
                </div>
                <div class='form-group col col-sm-2'>
                  <%= f.label :inquirier_kind_id_eq, '問合せ元分類' %>
                  <%= f.select :inquirier_kind_id_eq, @inquirier_kinds, { include_blank: 'すべて' }, { class: 'form-control' } %>
                </div>
                <div class="form-group col col-sm-5">
                  <%= label_tag :question_cont, '問合せ' %>
                  <%= text_field_tag :question_cont, '', class: 'form-control' %>
                </div>
              </div>

              <div class="row">              
                <div class="text-right">
                  <%= button_tag '検索', type: 'button', class: 'btn btn-success col col-sm-1', id: 'inquiry_search_btn' %>
                  <%= hidden_field_tag :search_url, '', id: 'search_url' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="modal-body p-0">
          <table class="table table-striped">
            <thead>
              <tr class="bg-secondary">
                <th>問合せ内容</th>
                <th>回答内容</th>
              </tr>
            </thead>

            <tbody id="searched_inquiries">
            </tbody>
          </table>
        </div>

        <div class="modal-footer">
          <%= button_tag '閉じる', type: 'button', class: 'btn btn-default modal_close', data: {:'bs-dismiss' => "modal"} %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(() => {
    const start_time = $('#timer').text().split(':');
    let hour = Number(start_time[0]);
    let min = Number(start_time[1]);
    let sec = Number(start_time[2]);

    function updateTimer() {
      ++sec;
      if (sec == 60) {
        sec = 0;
        ++min;
      }

      if (min == 60) {
        min = 0;
        ++hour;
      }

      const timer_text = zeroPadding(hour) + ":" + zeroPadding(min) + ":" +  zeroPadding(sec);
      $('#timer').text(timer_text);
    }

    function zeroPadding(time) {
      return ("00" + time).slice(-2);
    }

    setInterval(updateTimer, 1000);
  });

  $('#inquiry_search_btn').on('click', () => {
    const params = $('#search_form').serialize();
    $.ajax({
      type: 'GET',
      url: '/inquiries/inquiry_search',
      data: params,
      dataType: 'json'
    }).done((inquiries) => {
      removeRow();
      buildRow(inquiries);
    }).fail(() => {
      removeRow();
    })
  });

  function removeRow() {
    $('#searched_inquiries').children('tr').remove();
  }

  function buildRow(inquiries) {
    let html = '';
    $.each(inquiries, (i, data) => {
      html += '<tr>'
      html += '<td>' + data.question + '</td>';
      html += '<td>' + data.answer + '</td>';
      html += '</tr>'
    });

    $('#searched_inquiries').append(html);
  }
</script>

app/views/inquiries/unregister_inquiries.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <div class="container-fluid">
      <h4 class="m-0 text-dark">新着問合せ</h4>
    </div>
  </section>

  <section class="content">
    <div class="container-fluid">

      <% if @inquiries.present? %>
        <div class="card">
          <div class="card-body p-0">
            <div class="row">
              <% @inquiries.each do |inquiry| %>
                <div class="col col-sm-4">
                  <div class="card bg-light m-2">
                    <div class="card-body">
                      <ul class="list-group list-group-flush list-group-item-light">
                        <li class="list-group-item">
                          <i class="fas fa-clock mr-3"></i> <%= inquiry.inquiry_datetime %>
                        </li>
                        <li class="list-group-item">
                          <i class="fas fa-industry mr-3"></i> <%= inquiry.company_name %>
                        </li>
                        <li class="list-group-item">
                          <i class="fas fa-user-tie mr-3"></i> <%= inquiry.inquirier_name %>
                        </li>
                        <li class="list-group-item">
                          <i class="fas fa-phone mr-3"></i> <%= inquiry.telephone_number %>
                        </li>
                      </ul>
                    </div>

                    <div class="card-footer">
                      <div class="text-right">
                        <%= delete_button(unregister_destroy_inquiry_path(inquiry)) %>
                        <%= new_button(unregister_new_inquiries_path(id: inquiry.id), 'get', false, false) %>
                        <% if inquiry.can_resume? %>
                          <%= link_to '再開', unregister_edit_inquiry_path(inquiry), class: 'btn btn-success', data: {turbolinks: false} %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="ml-2">
            <%= paginate @inquiries %>
          </div>
        </div>
      <% else %>
        <%= render partial: 'shared/simple_error' %>
      <% end %>
    </div>
  </section>
</div>